### ISSUE TITLE
Broaden the manual regarding authoring prequeries

### ISSUE THREAD

**Issue by psads-git** [SillyFreak/typst-prequery#1]
I would like to suggest that the manual included more examples about authoring prequeries. For instance, it is not clear how to create a prequery for the following:

````
#import "@preview/prequery:0.1.0"

#metadata(
  ```python
  x = 2
  y = 3
  z = x + y
  ```
)

After doing the needed calculations, the result is #prequery.value(z)
````

Thanks!

**Comment by ensko** [comment]
Thanks for your interest! Right now, you definitely also need to look at the [source code](https://github.com/SillyFreak/typst-prequery/blob/main/src/lib.typ#L27-L89) to figure authoring your own prequeries out. I'm right now working on another tool that will make using existing prequeries easier, after that I can look at improving the docs. I'll try to explain here a bit, and please just ask if you need more info.

Authoring a prequery means creating a function that calls the `prequery` function, just like the `image` function in this package does. This function needs to
- provide the information for whatever preprocessor you want to run (the Python source code)
- identify the information with a label for your preprocessor to query
- specify where the result should be saved so that Typst can access it (a file name)

The `image` prequery looks like this:
```typ
#let image(url, ..args) = prequery(
  (url: url, path: args.pos().at(0)),
  <web-resource>,
  _builtin_image.with(..args),
  fallback: [\u{1F5BC}],
)
```
For you, that could look something like this:
```typ
#let python(raw-block, ..args) = prequery(
  (code: raw-block.text, path: args.pos().at(0)),
  <python>,
  read(..args),
  fallback: [</>],
)
```
by querying the document for `<python>`, you can get all the python codes and where to store the result; and Typst now knows how to load the result (I'm just using [`read`](https://typst.app/docs/reference/data-loading/read/), you may want something more specific). You could then call this like
````typ
#let z = python(
  ```
  x = 2
  y = 3
  z = x + y
  print(z)
  ```,
  "sum.txt"
)

After doing the needed calculations, the result is #z
````
(I added `print(z)` so that the script actually evaluates to something that can be saved to a file)

This does not cover actually executing Python code; helping with that is what the tool I'm working on is for.

I hope that helps; PS: I also want to point you at [pyrunner](https://typst.app/universe/package/pyrunner) if that's also something that could help you.

**Comment by psads-git** [comment]
Thanks a lot, @SillyFreak, for your very helpful answer! Your package is quite interesting!

I have tried the following code, but got errors:

````
#import "@preview/prequery:0.1.0"

#let python(raw-block, ..args) = prequery(
  (code: raw-block.text, path: args.pos().at(0)),
  <python>,
  read(..args),
  fallback: [</>],
)

#let z = python(
  ```
  x = 2
  y = 3
  z = x + y
  print(z)
  ```,
  "/sum.txt"
)

After doing the needed calculations, the result is #z
````

Errors:

```
$ typst query --input prequery-fallback=true --field value z.typ '<python>'
error: expected function, found module
  ┌─ z.typ:3:33
  │
3 │ #let python(raw-block, ..args) = prequery(
  │                                  ^^^^^^^^

help: error occurred in this call of function `python`
   ┌─ z.typ:10:9
   │  
10 │   #let z = python(
   │ ╭──────────^
11 │ │   ```
12 │ │   x = 2
13 │ │   y = 3
   · │
17 │ │   "/sum.txt"
18 │ │ )
   │ ╰─^

$

```

**Comment by ensko** [comment]
You need to call `prequery.prequery()`, or import like `#import "@preview/prequery:0.1.0": prequery`

**Comment by psads-git** [comment]
Thanks a lot, @SillyFreak! That works great and will be very helpful. 

Actually, I need to use pandas -- that is why `pyrunner` is not useful.

**Comment by ensko** [comment]
yeah, I imagined that libraries were the problem with pyrunner :)

The middle part - running the right Python commands from the queried JSON - will be your job for the time being. Feel free to reach out if you need anything else.

**Comment by psads-git** [comment]
Thanks, @SillyFreak! To deal with images, I had already found a way: [try and catch](https://sitandr.github.io/typst-examples-book/book/typstonomicon/try_catch.html), but your approach is more elegant.

**Comment by psads-git** [comment]
Hi Clements,

I have just tried the following code, and I get an error if `sum.txt` does not exist. Is such an error expected? 

Thanks!

````
#import "@preview/prequery:0.1.0": *

#let python(raw-block, ..args) = prequery(
  (code: raw-block.text, path: args.pos().at(0)),
  <python>,
  read(..args),
  fallback: [</>],
)

#let codez = ```py
  import pandas as pd
  import numpy as np

  df = pd.DataFrame({
    'A': ['Paulo', 'Antonio', 'Maria', 'Joaquim'], 
    'B': [4, 3, 2, 1], 
    'C': [4, 3, 2, 1], 
    'D': [4, 3, 2, 1]})
  print(df)
  ```
#let z1 = python(
  codez,
  "/sum.txt"
)

#let z2 = python(
  ```py
  print(df)
  ```,
  "/sum.txt"
)


After doing the needed calculations, the result is:

#z1, #z2
````

**Comment by ensko** [comment]
Yes, that's expected. You have to specify `--input prequery-fallback=true` to run your query, and after thus creating the files, compilation will work. That's what the fallback is for. (Written from memory; check the manual if this doesn't work as written)

Btw, you will need to specify different file names for the two programs, or one will overwrite the other.

**Comment by psads-git** [comment]
Thanks, Clemens, for your answer. I had already tried that, but got errors. Am I missing something?

```
$ typst query --input prequery-fallback=true --field value prequery01.typ '<python>'
error: file not found (searched at /home/x/programas/typst/sum2.txt)
   ┌─ prequery01.typ:30:2
   │
30 │   "/sum2.txt"
   │   ^^^^^^^^^^^

help: error occurred in this call of function `read`
  ┌─ prequery01.typ:6:2
  │
6 │   read(..args),
  │   ^^^^^^^^^^^^

$
```

**Comment by ensko** [comment]
Ah, sorry about that! In my initial code example, the original had `_builtin_image.with(..args)`. This needs to be mirrored: `read.with(..args)` (instead of `read(..args)`). This parameter needs to be a function that doesn't take parameters and, when called, reads the resource. without `with`, the file is _always_ read, and thus the query could never be executed (apart from the type being wrong).

**Comment by psads-git** [comment]
Thanks, Clemens, for your answer. Indeed, `read.with` works. However, the automatic preview of `Tinymist Typst Vs Code` extension fails:

```
error: file not found (searched at /home/x/programas/typst/sum2.txt)
   ┌─ /home/x/programas/typst/prequery01.typ:30:2
   │
30 │   "/sum2.txt"
   │   ^^^^^^^^^^^

help: error occurred in this call of function `read`
   ┌─ @preview/prequery:0.1.0/src/lib.typ:46:8
   │
46 │         body()
   │         ^^^^^^
```

I have tried, as suggested in the manual, the following code in the typst document:

```
#prequery.fallback.update(true)
```

but with no success:

```
error: cannot access fields on user-defined functions
   ┌─ /home/x/programas/typst/prequery01.typ:38:10
   │
38 │ #prequery.fallback.update(true)
   │           ^^^^^^^^

```

**Comment by ensko** [comment]
From your previous comment, it seems like you imported
```
#import "@preview/prequery:0.1.0": *
```
So you need to write `fallback` instead of `prequery.fallback`

**Comment by psads-git** [comment]
Thanks again, Clemens! It works the way you suggest, but the following does not work:

```
#import "@preview/prequery:0.1.0": prequery

#prequery.fallback.update(true)
```

Error:

```
[2024-07-23T14:34:29Z INFO  typst_ts_compiler::diag::console] Some(/prequery01.typ): compilation failed after 226.831µs
error: cannot access fields on user-defined functions
  ┌─ /home/x/programas/typst/prequery01.typ:3:10
  │
3 │ #prequery.fallback.update(true)
  │           ^^^^^^^^

[2024-07-23T14:34:29Z INFO  tinymist::actor::editor] received diagnostics from primary:143: diag(Some(1))

```

**Comment by ensko** [comment]
Please have a look at how imports work in the Typst docs. The `prequery` package declares a `prequery` function and `fallback` variable. The package and function are not interchangeable, and depending on how you write your import (your choice), you have to use the two definitions accordingly.

**Comment by psads-git** [comment]
Thanks, Clemens, for your help and for having created a so useful package!
